backend:
  name: github
  repo: 你的GitHub用户名/你的仓库名 # 例如：xutao/my-website
  branch: main
  site_domain: 你的网站域名 # 例如：xutao.github.io

media_folder: "images/uploads" # 上传的图片会存在这里
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "网站设置"
    files:
      - name: "basic"
        label: "基本信息"
        file: "data.json"
        fields:
          - {label: "姓名", name: "name", widget: "string"}
          - {label: "个人简介", name: "desc", widget: "text"}
          - {label: "作品集介绍", name: "portfolioIntro", widget: "text"}
          - {label: "电话", name: "phone", widget: "string"}
          - {label: "邮箱", name: "email", widget: "string"}
          - {label: "头像", name: "avatar", widget: "image"}

  - name: "portfolio"
    label: "作品集"
    folder: "data/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "描述", name: "description", widget: "text"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "分类", name: "categories", widget: "select", options: ["promo", "short", "ui", "photography"]}
      - {label: "封面图", name: "cover", widget: "image"}
