backend:
  backend:
  name: github
  repo: bxnfxzh-ui/你的仓库名  # 填入完整的仓库路径
  branch: main             # 确保分支名称正确

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "website_content"
    label: "网站内容管理"
    files:
      - name: "home_page"
        label: "首页编辑"
        file: "index.html"
        fields:
          - label: "首页大标题"
            name: "title"
            widget: "string"

          - label: "首页正文内容"
            name: "content"
            widget: "markdown"

          - label: "上传展示图片"
            name: "cover_img"
            widget: "image"

          - label: "上传网站视频"
            name: "video_file"
            widget: "file"
            multiple: false
